#!/bin/sh

EGET=/srv/danil/Projects/eget/eget

test_download(){
echo "Download $1"

MYDIR=./$(date +test-%H:%M:%S)
mkdir -p $MYDIR
MYFILE=$MYDIR/$(basename $1)
cd $MYDIR
$EGET $1
cd -
file $MYFILE
#rm -rf $MYDIR
}

test_download ftp://updates.etersoft.ru/pub/people/danil/Victor.jpg
test_download ftp://ftp.altlinux.ru/pub/docs/Heap/favicon.ico
test_download ftp://updates.etersoft.ru/pub/people/danil/eget_test2/*
test_download http://updates.etersoft.ru/pub/people/danil/eget_test2/*